### ISSUE TITLE
sorting is ignored when combined with lt()

### ISSUE THREAD

**Issue by hairmare** [libgraviton/php-rql-parser#21]
This is from [GRV-1497](https://issue.swisscom.ch/browse/GRV-1497?focusedCommentId=3357179&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-3357179) and pertains to `2.0.0-alpha1`.

Sorting seems to not work in combination with `lt()`. The following example is how this was reproduced.

```
lt(id,3),sort(-group)
```
- [ ] check if this was fixed in `2.0.0-alpha7`
- [ ] add test cases to `MongoDbVisitor`
- [ ] fix bug

**Comment by hairmare** [comment]
still needs retest from my POV

**Comment by hairmare** [comment]
Tested with http://graviton-develop.nova.scapp.io/core/app?q=lt(order,100)&sort(%2Border) and http://graviton-develop.nova.scapp.io/core/app?q=lt(order,100)&sort(-order)... Still broken, probably an issue with how the AST is being applied to the AST.

This problem probably has to do with the `Doctrine\ODM\MongoDB\Query\Expr` and maybe even with what is being done to the query builder before and/or after it is being passed into the visitor...

**Comment by mrix** [comment]
URL http://graviton-develop.nova.scapp.io/core/app?q=lt(order,100)&sort(%2Border) is invalid because "&" (ampersand) is not part of RQL query.
It should be http://graviton-develop.nova.scapp.io/core/app?q=lt(order,100)%26sort(%2Border)

**Comment by mrix** [comment]
Check https://github.com/libgraviton/php-rql-parser/pull/44

**Comment by hairmare** [comment]
so basically this was pebkac :) Thanks @mrix
