### ISSUE TITLE
make parser strategies configurable 

### ISSUE THREAD

**Issue by lapistano** [libgraviton/php-rql-parser#26]
it should be possible to configure the set of RQL-Parser-Strategies to be able to influence the parsing process.
It would further open the parser to other strategies without the need to change the implementation.

**Comment by hairmare** [comment]
This wasn't made configurable under the assumption that we don't need to change the available strategies during runtime and also that there won't be much changes to the strategies over time.

If you can sell me the business value of making this configurable I'll consider it. Currently I don't feel that making parser configurable adds much value.

**Comment by lapistano** [comment]
As I found out by deeper investigations, it is already possible using the `Parser::__construct()` and `Parser::addStrategy()` to add custom strategies. 
But I have to admit, if there is any named constructor (`Parser::createParser()`), I do not like that the class constructor is still public. 
If there would be a configuration for the Parser, it would be possible to rename the named constructor to `Parser::create($rql, Graviton\Rql\Parser\Strategy\ParsingStrategyInterface[] $strategies)` (this would free us from finding a better name for the old one ;) ) and the GravitonRQLBundle could be made aware of the possibility and provide the configuration for it.

**Comment by hairmare** [comment]
Yeah, the constructor should be private. We already agreed on this and it looks like a I simply forgot to do the change. In the end most you proposal does boil down to small semantic issues.

Nevertheless I still can't see a use case for not using all the available strategies. It we a tons of new strategies this case may arise and start making sense. We can still change it then.

One of the reasons to keep all the `addStrategy` calls in `createParser` was to ensure that we don't need to add new strategies in the bundle as well each time.

**Comment by lapistano** [comment]
I see your point, but it will prevent every one else with a need for his own implementations to inject them, at least, if the constructor is not public any more. 
I am not saying this has to be done now, since this is an enhancement proposal, it can be done any time. 
The business case here is to open the usage of the Parser to more than the provided strategies, so more people might be able to use this library.

**Comment by hairmare** [comment]
I see your point and I'm not against doing this. It's just we need to implement sugar syntax, add heaps more strategies and make this completely useable for our cases first...

**Comment by hairmare** [comment]
Not relevant anymore since we switched to https://github.com/xiag-ag/rql-parser
