### ISSUE TITLE
test dues are overdue

### ISSUE THREAD

**Issue by hairmare** [libgraviton/php-rql-parser#4]
This module needs acceptance, unit testing as well as some basic qa. For starters I believe we will need to implement the following.
- Unit tests that tests the parser agains a mocked instance of `Graviton\Rql\QueryInterface`. This should cover all the code except `Graviton\Rql\Queriable\MongoOdm`.
- Acceptance tests that test `Graviton\Rql\Queriable\MongoOdm` mocked (or even faked) data.
- CodeSniffer and PMD reports that are run on build with sensible error/warn conditions.

**Comment by hairmare** [comment]
I already started with implementation in https://github.com/libgraviton/php-rql-parser/tree/feature/phpunit-integration.

**Comment by narcoticfresh** [comment]
yes, this needs some tests for sure..

imho it should suffice to create an implementation of our interface that tracks the calls made to it and test with that (calling will all valid expressions) - we shouldn't really need to mock the mongodb one as it's basically just an example implementation of business logic using the lib..

maybe if one day we ship a collection of production ready implementations, we can consider adding tests for them..

**Comment by hairmare** [comment]
I'm OK with skipping the integrations tests for the time being. It won't however be production ready without those tests.

I would like to get up to speed on this lib ASAP, thus enabling us to merge the changes in https://github.com/izziaraffaele/php-rql-parser. They seem to implement more of the spec, but also contain a Queriable that probably won't be much use for us.
